Feature
certilremy/project_enumerable_methods pull request #1
Opened 2020-01-24 22:58 UTC by certilremy

Added All requirement

2020-01-25 03:19 UTC, whiz25 requested changes
## Nice progress @certilremy :+1: 
Your project looks good. I tested your methods against some edge cases and we can fix a few things before merging.
- [ ] The project should have a descriptive README.md ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/descriptive_readme.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))
- [ ] Pull Request should have a meaningful title and a short description ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/descriptive_prs.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))
- [ ] Make your commits more descriptive ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/descriptive_commits.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))
#### Read more of my comments for suggestions

### Martin Afani

2020-01-25 03:26 UTC, whiz25 commented on lib/main.rb
> +  end
- [ ] should be identical and returns the same thing as ruby's [`each`](https://ruby-doc.org/core-2.6.4/Array.html#method-i-each). ([Screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/advanced_building_blocks_enumerable/my_each.png) from [Odin](https://www.theodinproject.com/courses/ruby-programming/lessons/advanced-building-blocks#assignment-2))
- [ ] returns an Enumerator if no block is given
You can achieve that by doing something like this;
```ruby
def my_each
    if block_given?
      .....
    else
      return to_enum
end

2020-01-25 03:28 UTC, whiz25 commented on lib/main.rb
> +  end
- [ ] should be identical and returns the same thing as ruby's [`each_with_index`](https://ruby-doc.org/core-2.6.4/Enumerable.html#method-i-each_with_index). ([Screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/advanced_building_blocks_enumerable/my_each_with_index.png) from [Odin](https://www.theodinproject.com/courses/ruby-programming/lessons/advanced-building-blocks#assignment-2))
- [ ]  my_each_with_index returns an enumerator if no block is given
  ```ruby 
  array = [1,2,5,8,7,98,4]
  p array.my_each_with_index.class # not Enumerator

2020-01-25 03:30 UTC, whiz25 commented on lib/main.rb
> +  end
- [ ] should be identical and returns the same thing as ruby's [`select`](https://ruby-doc.org/core-2.6.4/Enumerable.html#method-i-select). ([Screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/advanced_building_blocks_enumerable/my_select.png) from [Odin](https://www.theodinproject.com/courses/ruby-programming/lessons/advanced-building-blocks#assignment-2))
- [ ] my_select returns an array containing all elements of enum for which the given block returns a true value
  ```ruby
  block = proc {|x| x>4}
  array = [1,2,5,8,7,98,4]
  p array.my_select(&block) == array.select(&block) # false
- [ ] my_select returns an enumerator if no block is given
  ```ruby
  array = [1,2,5,8,7,98,4]
  p array.my_select.class # not Enumerator

2020-01-25 03:35 UTC, whiz25 commented on lib/main.rb
> +  end
- [ ] should be identical and returns the same thing as ruby's [`all?`](https://ruby-doc.org/core-2.6.4/Enumerable.html#method-i-all-3F). ([Screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/advanced_building_blocks_enumerable/my_all.png) from [Odin](https://www.theodinproject.com/courses/ruby-programming/lessons/advanced-building-blocks#assignment-2))
- [ ]  my_all? when a class is passed as an argument returns true if all of the collection is a member of such class
  ```ruby
  array = [1,2,5,4,7]
  p array.my_all?(Integer) == array.all?(Integer) # false
- [ ] my_all? when no block or argument is given returns true when none of the collection members are false or nil
  ```ruby
  array = [1,2,5,4,7]
  p array.my_all? == array.all? # false
- [ ] my_all? when a Regex is passed as an argument returns true if all of the collection matches the Regex
  ```ruby
  array = %w[dog door rod blade]
  p array.my_all?(/c/) == array.all?(/c/) # false
- [ ] my_all? when a pattern other than Regex or a Class is given returns true if all of the collection matches the pattern
  ```ruby
  array = %w[dog door rod blade]
  p array.my_all?(5) == array.all?(5) # false

2020-01-25 03:43 UTC, whiz25 commented on lib/main.rb
> +  end
- [ ] should be identical and returns the same thing as ruby's [`any?`](https://ruby-doc.org/core-2.6.4/Enumerable.html#method-i-any-3F). ([Screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/advanced_building_blocks_enumerable/my_any.png) from [Odin](https://www.theodinproject.com/courses/ruby-programming/lessons/advanced-building-blocks#assignment-2))
- [ ] when no block or argument is given returns true if at least one of the collection is not false or nil
 ```ruby 
  array = [nil, false, true, []]
  p array.my_any? == array.any? # false
```
- [ ]  when a Regex is passed as an argument returns false if none of the collection matches the Regex
  ```ruby
  array = %w[dog door rod blade]
  p array.my_any?(/c/) == array.any?(/c/) # false
  ```
 - [ ] when a pattern other than Regex or a Class is given returns false if none of the collection matches the pattern
  ```ruby
  array = %w[dog door rod blade]
  p array.my_any?(5) == array.any?(5) # false
 ```

2020-01-25 03:47 UTC, whiz25 commented on lib/main.rb
> +  end
- [ ] should be identical and returns the same thing as ruby's [`none?`](https://ruby-doc.org/core-2.6.4/Enumerable.html#method-i-none-3F). ([Screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/advanced_building_blocks_enumerable/my_none.png) from [Odin](https://www.theodinproject.com/courses/ruby-programming/lessons/advanced-building-blocks#assignment-2))
- [ ] my_none? when no block or argument is given returns true only if none of the collection members is true
```ruby
  array = [1,2,5,4,7]
  p array.my_none? == array.none? # false
```
- [ ] when a class is passed as an argument returns true if none of the collection is a member of such class
```ruby
  array = [1,2,5,4,7]
  p array.my_none?(Integer) == array.none?(Integer) # false
```
- [ ] when a Regex is passed as an argument returns true only if none of the collection matches the Regex
```ruby
  array = %w[dog door rod blade]
  p array.my_none?(/c/) == array.none?(/c/) # false
```
 - [ ] when a pattern other than Regex or a Class is given returns true only if none of the collection matches the pattern
```ruby
  array = %w[dog door rod blade]
  p array.my_none?(5) == array.none?(5) # false
```

2020-01-25 03:49 UTC, whiz25 commented on lib/main.rb
> +  end
- [ ] should be identical and returns the same thing as ruby's [`map`](https://ruby-doc.org/core-2.6.4/Enumerable.html#method-i-map). ([Screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/advanced_building_blocks_enumerable/my_map.png) from [Odin](https://www.theodinproject.com/courses/ruby-programming/lessons/advanced-building-blocks#assignment-2))
- [ ] returns an Enumerator if no block is given
```ruby
 array = [1,5,8,7,9,5,5,55,5]
 p array.my_map #error
 LocalJumpError:
     no block given (yield)
```

2020-01-25 03:51 UTC, whiz25 commented on lib/main.rb
> +end
- [ ] should be identical and returns the same thing as ruby's [`inject`](https://ruby-doc.org/core-2.6.4/Enumerable.html#method-i-inject). ([Screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/advanced_building_blocks_enumerable/my_inject.png) from [Odin](https://www.theodinproject.com/courses/ruby-programming/lessons/advanced-building-blocks#assignment-2))
- [ ] my_inject combines all elements of enum by applying a binary operation, specified by a block
```ruby
  range = Range.new(5, 50)
  p range.my_inject(4) { |prod, n| prod * n } # returns this error
  # NoMethodError:
     #  undefined method `length' for 5..50:Range
    # ./enumerables.rb:76:in `my_inject'
```
- [ ] my_inject when a symbol is specified combines each element of the collection by applying the symbol as a named method
```ruby
  array = [1,7,8,89,9,6,5,12,4,2,5]
  p array.my_inject(:+) == array.inject(:+) # return this error
  # LocalJumpError:
     # no block given (yield)
    # ./enumerables.rb:78:in `block in my_inject'
    # ./enumerables.rb:76:in `each'
    # ./enumerables.rb:76:in `my_inject'
```

2020-01-27 18:42 UTC, whiz25 requested changes
## Hey @certilremy 
I know you have made some changes that are good but your methods still fail against the same edge cases I pointed out in my previous review.
Check my suggestions again from the previous review. Take your time and make sure everything works well before submitting it for another review.

### Martin Afani

2020-01-27 19:21 UTC, certilremy commented
> ## Hey @certilremy
> I know you have made some changes that are good but your methods still fail against the same edge cases I pointed out in my previous review.
> Check my suggestions again from the previous review. Take your time and make sure everything works well before submitting it for another review.
> 
> ### Martin Afani

Thank you for your feedback. I didn't quite understand what you need me to do. I read and read the project from the Odin project I can't see it.

2020-01-27 22:06 UTC, suretrust requested changes
Hi @certilremy, :wave: 

### Great job thus far! :raised_hands: Please see my comments on your code. :point_down: 

**Kindly submit for another code review once these have been fixed.** _Happy coding!_ :tada:

2020-01-27 22:06 UTC, suretrust commented on lib/main.rb
> +  end
* [ ] should have working `my_select` **(covered by automated tests)** identical and returns the same thing as ruby's [`select`](https://ruby-doc.org/core-2.6.4/Enumerable.html#method-i-select). ([Screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/advanced_building_blocks_enumerable/my_select.png) from [Odin](https://www.theodinproject.com/courses/ruby-programming/lessons/advanced-building-blocks#assignment-2))
* [ ] enumerables my_select returns an array containing all elements of enum for which the given block returns a true value
```ruby
[1, 2, 3, 4, 5, 6, 7, 8, 9].select { |num| num < (1 + 9) / 2 } != [1, 2, 3, 4, 5, 6, 7, 8, 9].my_select { |num| num < (1 + 9) / 2 }
```

2020-01-27 22:06 UTC, suretrust commented on lib/main.rb
> +    end
* [ ] should have working `my_any?` **(covered by automated tests)** identical and returns the same thing as ruby's [`any?`](https://ruby-doc.org/core-2.6.4/Enumerable.html#method-i-any-3F). ([Screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/advanced_building_blocks_enumerable/my_any.png) from [Odin](https://www.theodinproject.com/courses/ruby-programming/lessons/advanced-building-blocks#assignment-2))

- [ ] enumerables my_all? when a pattern other than Regex or a Class is given returns true if all of the collection matches the pattern
```ruby
[0,1,2,3,4,5,6,7,8,9].my_all?(3) != [0,1,2,3,4,5,6,7,8,9].all?(3)
```

2020-01-27 22:06 UTC, suretrust commented on lib/main.rb
> +  end
* [ ] should have working `my_any?` identical and returns the same thing as ruby's [`any?`](https://ruby-doc.org/core-2.6.4/Enumerable.html#method-i-any-3F). ([Screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/advanced_building_blocks_enumerable/my_any.png) from [Odin](https://www.theodinproject.com/courses/ruby-programming/lessons/advanced-building-blocks#assignment-2))

- [ ] enumerables my_any? when a pattern other than Regex or a Class is given returns false if none of the collection matches the pattern
```ruby
['saheed','oladele','suretrust'].my_any?('cat') != ['saheed','oladele','suretrust'].any?('cat')
```

2020-01-27 22:06 UTC, suretrust commented on lib/main.rb
> +  end
* [ ] should have working `my_none?` identical and returns the same thing as ruby's [`none?`](https://ruby-doc.org/core-2.6.4/Enumerable.html#method-i-none-3F). ([Screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/advanced_building_blocks_enumerable/my_none.png) from [Odin](https://www.theodinproject.com/courses/ruby-programming/lessons/advanced-building-blocks#assignment-2))

- [ ] enumerables my_none? when a pattern other than Regex or a Class is given returns true only if none of the collection matches the pattern
```ruby
['saheed','oladele','suretrust'].my_none?(5) != ['saheed','oladele','suretrust'].none?(5)
```

2020-01-27 22:06 UTC, suretrust commented on lib/main.rb
> +    return total = lenght unless block_given?
`length` typo-ed as `lenght`

2020-01-27 22:06 UTC, suretrust commented on lib/main.rb
> +    end
* [ ] should have working `my_inject` identical and returns the same thing as ruby's [`inject`](https://ruby-doc.org/core-2.6.4/Enumerable.html#method-i-inject). ([Screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/advanced_building_blocks_enumerable/my_inject.png) from [Odin](https://www.theodinproject.com/courses/ruby-programming/lessons/advanced-building-blocks#assignment-2))

- [ ] Enumerables my_inject combines all elements of enum by applying a binary operation, specified by a block.
```ruby
[1,2,3,4,5].my_inject(&:+) != [1,2,3,4,5].inject(&:+)
```

- [ ] Enumerables my_inject, when a symbol is specified, combines each element of the collection by applying the symbol as a named method.
```ruby
[1,2,3,4,5].my_inject(:+) != [1,2,3,4,5].inject(:+)
```

2020-01-28 03:16 UTC, whiz25 requested changes
## Good Progress @certilremy :+1: 
You have made a tremendous progress in this project. Let's fix the remaining failing edge cases so we can merge. 
- [ ] my_select returns an array containing all elements of enum for which the given block returns a true value
- [ ] my_all? when a pattern other than Regex or a Class is given returns true if all of the collection matches the pattern
- [ ] my_any? when a pattern other than Regex or a Class is given returns false if none of the collection matches the pattern
- [ ] my_none? when a pattern other than Regex or a Class is given returns true only if none of the collection matches the pattern
- [ ] my_count counts the number of items in enum that are equal to item if an argument is given
- [ ] my_inject combines all elements of enum by applying a binary operation, specified by a block
rspec ./spec/test_spec.rb:215 # enumerables 
- [ ] my_inject when a symbol is specified combines each element of the collection by applying the symbol as a named method

### Martin Afani

2020-01-28 03:24 UTC, whiz25 commented
> > ## Hey @certilremy
> > I know you have made some changes that are good but your methods still fail against the same edge cases I pointed out in my previous review.
> > Check my suggestions again from the previous review. Take your time and make sure everything works well before submitting it for another review.
> > ### Martin Afani
> 
> Thank you for your feedback. I didn't quite understand what you need me to do. I read and read the project from the Odin project I can't see it.

What I mean was that some of your methods were not behaving like the original ruby methods. For example, your `my_map` was not giving the same result as the built-in `map` method.
This is something that I pointed out in my first review of your PR. So on testing your methods again against some tests, I still getting the same result like begore event after the changes you made.
This is why I referred you to the first review.

2020-01-28 17:14 UTC, stratospherique requested changes
### Amazing work implementing the suggested changes :clap:  :clap: However, I got some cases in which `my_inject` doesn't behave the way it should be. Check :arrow_down: 

- **[REQUIRED]** Check the code comments below, they should help you refactor your method :nerd_face: 

### That's it :relieved: When finished, kindly resubmit another code review request :pray: 

Happy coding :v: 
**_Ahmed Mahfoudh_**

2020-01-28 17:14 UTC, stratospherique commented on lib/main.rb
> +end
* [ ] my_inject combines all elements of enum by applying a binary operation, specified by a block
  ```ruby
    range = Range.new(5, 50)
    p range.my_inject(4) { |prod, n| prod * n } # returns this error
    # NameError:
       undefined local variable or method `length' for 5..50:Range
     # ./lib/main.rb:121:in `my_inject'
  ```

* [ ] my_inject when a symbol is specified combines each element of the collection by applying the symbol as a named method
  ```ruby
    range = Range.new(5, 50)
    p range.my_inject(2, :*) # returns this error
    # NameError:
       undefined local variable or method `ind' for 5..50:Range
       Did you mean?  find
                      end
                      end
                      and
                      END
     # ./lib/main.rb:154:in `my_inject'
  ```

2020-01-28 18:07 UTC, Forison requested changes
## Status: Require Changes🛑
## Hi @certilremy,
I can see you have come a long a way🙂, That is the spirit, coding is all bout problem-solving🙂.
The issue raised in the last review still prevails🤔, check below for comment on the error👇
# Kindly make changes and submit the project for review
## Happy coding💪
## Addo Forison

2020-01-28 18:07 UTC, Forison commented on lib/main.rb
> +      while index < length
* [ ] length is undefined kindly rectify it.
 ```
range = Range.new(5, 50)
p range.my_inject(4) { |prod, n| prod * n }
range_two = Range.new(5, 50)
p range_two.my_inject(2, :*)
 ``` 
returns
 ```main.rb:122:in `my_inject': undefined local variable or method `length' for 5..50:Range (NameError) ```

2020-01-28 19:38 UTC, shshamim63 commented
## Status :heavy_check_mark: [Approved] :heavy_check_mark: 
___
Hi @certilremy :wave: ,
Project contains descriptive readme, you have covered all the changes asked by the previous reviewer. All the methods are working properly. Awesome job :clap: . 
___
### This :+1: is from me. You can merge it. and don't forget to fill the project completion form.
___
## :herb: Happy Coding :herb: 
### Shakhawat Hossain
[Linkedin](https://www.linkedin.com/in/shakhawathossainshamim/)

2020-01-28 19:38 UTC, merged